version: "3.9"

services:
  itak-postgres:
    image: postgres:15
    container_name: itak-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: itak_manager
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: sangamer77/itakapp-backend:latest
    container_name: itak-manager-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - itak-postgres

  frontend:
    image: sangamer77/itakapp-frontend:latest
    container_name: itak-manager-frontend
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata:
